<?php include('nav.php')?>
<h1 >Welcome to Spark Bank</h1>
<div class="bg">
  <div class="center">
    <!--START BUTTONS -->
    <ul>
      <!-- FIRST -->
        <a class="oprations" href = "transfer_money.php">
          <button class="btn" id="red">View all Users</button>
        </a>
      <!-- SECAND -->
        <a class="oprations" href = "transfer_money.php">
          <button class="btn" id="blue">Transfer Money</button>
        </a>
      <!-- THIRD -->
        <a class="oprations" href = "transactionhistory.php">
          <button class="btn" id="green">View Transfer History</button>
        </a>
      <!-- END BUTTONS -->
    </ul>
  </div>
</div>
<?php include('footer.php')?>

