 <!DOCTYPE html>
  <html>
  <style>
     .navbar{
      background-image: linear-gradient(#112B3C,#205375);
      height: 85px;
      font-family: 'Poppins', sans-serif;
     }
     .navbar li{
      list-style: none;
      display: inline;
     }
     li a{
      color: white;
      float: right;
      padding-right: 25px;
      font-size: 20px;
      border: none;
      font-weight: 500;
      transition: 3s ease color;
     }
     .navbar li a:hover{
      border-bottom: 1px solid grey;
      font-weight: 999;
      color: #FAFFAF;
     }
     .navbar img{
      margin-left: 25px;
     } 
  </style>
  <head>
     <meta charset="utf-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>Sparks Bank</title>
     <link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.min.css">
     <link rel="stylesheet" type="text/css" href="css/index.css">
     <link rel="stylesheet" type="text/css" href="css/table.css">
     <link rel="stylesheet" type="text/css" href="css/createuser.css">
     <link rel="stylesheet" type="text/css" href="css/contact.css">
     <link rel="stylesheet" type="text/css" href="css/transactionhistory.css">
     <script type="text/javascript" src="bootstrap/js/bootstrap.bundle.min.js"></script>
     <link rel = "icon" href = "img/logo.png" type = "image/x-icon">
  </head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark">
   <div class="container-fluid">
      <a class="navbar-brand logo" href="index.php">
         <img src="img/logo.png" alt="logo" height=50px width=50px>
      </a>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
         <ul class="navbar-nav">
            <li class="nav-item btn btn-secondary">
               <a class="nav-link link-text text-white" href="contactme.php">Contact me</a>
            </li>
            <li class="nav-item btn btn-secondary">
               <a class="nav-link link-text text-white" target="_blank" href="https://shruti8911.github.io/My_Portfolio/">About Me</a>
            </li>
            <li class="nav-item btn btn-secondary">
               <a class="nav-link text-white" href="index.php">Home</a>
            </li>
        </ul>
      </div>
   </div>
</nav>
</body>
</html>
  